Microsoft Windows [Version 10.0.19044.2006]
(c) Microsoft Corporation. All rights reserved.

C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>code.
'code.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>python manger.py runserver
python: can't open file 'manger.py': [Errno 2] No such file or directory

C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>python manager.py runserver
python: can't open file 'manager.py': [Errno 2] No such file or directory

C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 22, 2022 - 10:42:30
Django version 2.2.4, using settings 'DojoSurvey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 22, 2022 - 10:42:43
Django version 2.2.4, using settings 'DojoSurvey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Sep/2022 10:42:53] "GET / HTTP/1.1" 200 2382
[22/Sep/2022 10:42:53] "GET /static/style.css HTTP/1.1" 304 0
Not Found: /favicon.ico
[22/Sep/2022 10:42:54] "GET /favicon.ico HTTP/1.1" 404 2170
[22/Sep/2022 10:43:06] "POST /result HTTP/1.1" 200 1005
^C
C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>

C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>"C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\my_environments\djangoPy3Env\Scripts\activate"
(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 22, 2022 - 10:43:37
Django version 2.2.4, using settings 'DojoSurvey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Sep/2022 10:43:44] "GET / HTTP/1.1" 200 2382

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\DojoSurvey>cd ..

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro>cd Codeing
The system cannot find the path specified.

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro>cd Coding

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 22, 2022 - 10:47:13
Django version 2.2.4, using settings 'DojoSurvey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Sep/2022 10:47:17] "GET / HTTP/1.1" 200 2366
[22/Sep/2022 10:47:20] "GET / HTTP/1.1" 200 2366
[22/Sep/2022 10:47:20] "GET / HTTP/1.1" 200 2366
[22/Sep/2022 10:47:20] "GET / HTTP/1.1" 200 2366
[22/Sep/2022 10:47:20] "GET / HTTP/1.1" 200 2366
Internal Server Error: /result
Traceback (most recent call last):
  File "C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'fav_language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\my_environments\djangoPy3Env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\my_environments\djangoPy3Env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\my_environments\djangoPy3Env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding\firstapp\views.py", line 11, in create_user
    fav=request.POST['fav_language']
  File "C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\my_environments\djangoPy3Env\lib\site-packages\django\utils\datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'fav_language'
[22/Sep/2022 10:47:27] "POST /result HTTP/1.1" 500 81182
[22/Sep/2022 10:47:33] "POST /result HTTP/1.1" 200 1003
[22/Sep/2022 10:47:52] "POST /result HTTP/1.1" 200 1003
[22/Sep/2022 10:47:52] "GET /static/style.css HTTP/1.1" 200 536
Not Found: /favicon.ico
[22/Sep/2022 10:47:52] "GET /favicon.ico HTTP/1.1" 404 2170
[22/Sep/2022 10:47:56] "GET / HTTP/1.1" 200 2366
[22/Sep/2022 10:47:56] "GET /static/style.css HTTP/1.1" 200 536
Not Found: /favicon.ico
[22/Sep/2022 10:47:56] "GET /favicon.ico HTTP/1.1" 404 2170
C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding\firstapp\models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 22, 2022 - 10:52:16
Django version 2.2.4, using settings 'DojoSurvey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding>
(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding>
(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding> python manage.py makemigrations
Migrations for 'firstapp':
  firstapp\migrations\0001_initial.py
    - Create model Users

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, firstapp, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying firstapp.0001_initial... OK
  Applying sessions.0001_initial... OK

(djangoPy3Env) C:\Users\2019\Desktop\Coding Dojo\Python Stack\python_stack\django\django_intro\Coding> python manage.py shell
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from firstapp.models import *
>>> Users.objects.create(first_name="Ahmad",last_name="sami",email="ee@example.come",age=20)
<Users: Users object (1)>
>>> Users.objects.create(first_name="sami",last_name="saedd",email="ahmad@example.come",age=22)
<Users: Users object (2)>
>>> Users.objects.create(first_name="sameer",last_name="saedd",email="ss@example.come",age=22)
<Users: Users object (3)>
>>> Users.objects.all()
<QuerySet [<Users: Users object (1)>, <Users: Users object (2)>, <Users: Users object (3)>]>
>>> Users.objects.all().values()
<QuerySet [{'id': 1, 'first_name': 'Ahmad', 'last_name': 'sami', 'email': 'ee@example.come', 'age': 20, 'created_at': datetime.datetime(2022, 9, 22, 8, 2, 55, 625117, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 2, 55, 625117, tzinfo=<UTC>)}, {'id': 2, 'first_name': 'sami', 'last_name': 'saedd', 'email': 'ahmad@example.come', 'age': 22, 'created_at': datetime.datetime(2022, 9, 22, 8, 3, 22, 550658, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 3, 22, 550658, tzinfo=<UTC>)}, {'id': 3, 'first_name': 'sameer', 'last_name': 'saedd', 'email': 'ss@example.come', 'age': 22, 'created_at': datetime.datetime(2022, 9, 22, 8, 3, 35, 42079, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 3, 35, 42079, tzinfo=<UTC>)}]>
>>> Users.objects.last()
<Users: Users object (3)>
>>> Users.objects.last().__dict__
{'_state': <django.db.models.base.ModelState object at 0x000001969FEE7EB8>, 'id': 3, 'first_name': 'sameer', 'last_name': 'saedd', 'email': 'ss@example.come', 'age': 22, 'created_at': datetime.datetime(2022, 9, 22, 8, 3, 35, 42079, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 3, 35, 42079, tzinfo=<UTC>)}
>>> Users.objects.first().__dict__
{'_state': <django.db.models.base.ModelState object at 0x000001969FEE7F28>, 'id': 1, 'first_name': 'Ahmad', 'last_name': 'sami', 'email': 'ee@example.come', 'age': 20, 'created_at': datetime.datetime(2022, 9, 22, 8, 2, 55, 625117, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 2, 55, 625117, tzinfo=<UTC>)}
>>> c =Users.objects.get(id=3)
>>> c.last_name="Pancakes"
>>> c.save()
>>> Users.objects.get(id=3)
<Users: Users object (3)>
>>> Users.objects.get(id=3).__dict__
{'_state': <django.db.models.base.ModelState object at 0x000001969FF053C8>, 'id': 3, 'first_name': 'sameer', 'last_name': 'Pancakes', 'email': 'ss@example.come', 'age': 22, 'created_at': datetime.datetime(2022, 9, 22, 8, 3, 35, 42079, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 7, 13, 70086, tzinfo=<UTC>)}
>>> c =Users.objects.get(id=2)
>>> c.delee()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Users' object has no attribute 'delee'
>>> c.delete()
(1, {'firstapp.Users': 1})
>>> Users.objects.all().order_by("first_name")
<QuerySet [<Users: Users object (1)>, <Users: Users object (3)>]>
>>> Users.objects.all().order_by("first_name").__dict__
{'model': <class 'firstapp.models.Users'>, '_db': None, '_hints': {}, 'query': <django.db.models.sql.query.Query object at 0x000001969FEBF908>, '_result_cache': None, '_sticky_filter': False, '_for_write': False, '_prefetch_related_lookups': (), '_prefetch_done': False, '_known_related_objects': {}, '_iterable_class': <class 'django.db.models.query.ModelIterable'>, '_fields': None}
>>> Users.objects.all().order_by("-first_name").__dict__
{'model': <class 'firstapp.models.Users'>, '_db': None, '_hints': {}, 'query': <django.db.models.sql.query.Query object at 0x000001969FEE7F28>, '_result_cache': None, '_sticky_filter': False, '_for_write': False, '_prefetch_related_lookups': (), '_prefetch_done': False, '_known_related_objects': {}, '_iterable_class': <class 'django.db.models.query.ModelIterable'>, '_fields': None}
>>> Users.objects.all().order_by("-first_name").values()
<QuerySet [{'id': 3, 'first_name': 'sameer', 'last_name': 'Pancakes', 'email': 'ss@example.come', 'age': 22, 'created_at': datetime.datetime(2022, 9, 22, 8, 3, 35, 42079, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 7, 13, 70086, tzinfo=<UTC>)}, {'id': 1, 'first_name': 'Ahmad', 'last_name': 'sami', 'email': 'ee@example.come', 'age': 20, 'created_at': datetime.datetime(2022, 9, 22, 8, 2, 55, 625117, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 22, 8, 2, 55, 625117, tzinfo=<UTC>)}]>
>>>